apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-message
  labels:
    app: tech-challenge-message
spec:
  template:
    metadata:
      name: tech-challenge-message
      labels:
        app: tech-challenge-message
    spec:
      containers:
        - name: tech-challenge-message-api
          image: 851725563168.dkr.ecr.us-east-1.amazonaws.com/message-service:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 40
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          env:
            - name: RESEND_KEY
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-message-secret
                  key: RESEND_KEY
            - name: EMAIL_DEFAULT
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-message-secret
                  key: EMAIL_DEFAULT
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-message-secret
                  key: AMQP_URL
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-message