version: '3'
services:
  message-service-nest:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
